service: recursive

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 10

functions:
  HttpListener:
    role: arn:aws:iam::355151872526:role/queueLamda
    handler: triggers/http.handler
    events:
    - http:
        path: image
        method: get
  MessageListener:
    timeout: 40
    memorySize: 2000
    role: arn:aws:iam::355151872526:role/queueLamda
    handler: triggers/message.handler
    events:
    - sqs:
        queueName: recursive
        arn: arn:aws:sqs:ap-southeast-2:355151872526:recursive.fifo
        batchSize: 1